#### Data Enncryption and Decryption
- Encryption is a security method in which information is encoded in such a way that only authorised user can read  it.
- It uses encryption algorithm to generate ciphertext that can only be read if decrypted

- Decryption is the process of taking encoded or encrpted text and converted it back into text you or the computer can read and understand
* Type : Symmetric (Private Key ) and Asymmetric (Public key)
    * Symmetric :
        - It uses a Single key that will be shared among the people who read to receive the message 

In [3]:
# function to generate key for encryption
keypath = 'DataFiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
            if i < 6:
                f.write(str(i)+' '+str(i+4)+'\n')
            else:
                f.write(str(i)+' '+str(i-6)+'\n')
    return
generatekey(keypath)

In [5]:
#function to decrypt a DataFile
keyfile = 'DataFiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
            if i >6 :
                f.write(str(i)+' '+str(i-4)+'\n')
            else :
                f.write(str(i)+' '+str(i+6)+'\n')
    return
generatekey(keypath)

### program to print the given list into an array using the numpy

In [2]:
import numpy as np
li = [1,2,3,'z']
a = np.array(li)
print(a)

['1' '2' '3' 'z']


In [3]:
import numpy as np
array_2d = np.array([[2,3,4],[5,8,7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


In [6]:
import numpy as np
li = [1,2,3,4.0,'o']
a = np.array(li)
a
print(a)
type(a)

['1' '2' '3' '4.0' 'o']


numpy.ndarray

In [8]:
import numpy as np 
a2 = np.arange(10000)
a2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [9]:
a2 = np.arange(10000).reshape(100,100)
a2

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [10]:
import numpy as np


In [11]:
array1 = [[1,2,3,4],[5,6,7,8]]
a1 = np.array(array1)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
print("shape:",a1.shape)
print("data type:",a1.size)
print(a1)

shape: (2, 4)
data type: 8
[[1 2 3 4]
 [5 6 7 8]]


-program to create an array by taking range of array and reshape i

 - Create an array of 1's.Take a list & convert it into a 3D array and add 1 to each element in an array

In [14]:
b = [[1,2,3],[10,20,30],[11,22,33]]
c = np.array(b)
c

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 22, 33]])

In [15]:
d = c+1
d

array([[ 2,  3,  4],
       [11, 21, 31],
       [12, 23, 34]])

In [18]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(5,11).reshape(2,3)
print(a,)
print(b,'\n')
print(a+b)
print(a/b)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]] 

[[ 6  8 10]
 [12 14 16]]
[[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [ ]:
- program to apply 